version: '3.8'

services:
  redis:
    image: redis:latest
    container_name: redis-server
    ports:
      - "6379:6379"
    networks:
      - red_ej2
    restart: always

networks:
  red_ej2:
    external: true